
name: Maven CI/CD

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Cjeckout the repo
      uses: actions/checkout@3
      with:
      	persist-credentials: false
        ref: ${{ github.event.inputs.checkoutRef}}
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@4
      with:
        java-version: 21

    - name: clean_install
      run: mvn clean install
      
    - name: Build project with Maven
      run: mvn -B package --file pom.xml